<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T86_groups_model extends CI_Model
{

    public $table = 't86_groups';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id,name,description');
        $this->datatables->from('t86_groups');
		if (isset($_POST['id']) && $_POST['id'] != '') { $this->datatables->like('id', $_POST['id']); }
		if (isset($_POST['name']) && $_POST['name'] != '') { $this->datatables->like('name', $_POST['name']); }
		if (isset($_POST['description']) && $_POST['description'] != '') { $this->datatables->like('description', $_POST['description']); }
        //add this line for join
        //$this->datatables->join('table2', 't86_groups.field = table2.field');
        //$this->datatables->add_column('action', anchor(site_url('t86_groups/update/$1'),'Ubah')." | ".anchor(site_url('t86_groups/delete/$1'),'Hapus','onclick="javascript: return confirm(\'Apakah Anda yakin ingin menghapus data ?\')"'), 'id');
        $action = "";
        $hakAkses = $this->session->userdata('hakAkses'.substr($this->uri->segment(1), 4));
        if ($hakAkses['ubah']) {
            $action = anchor(site_url('t86_groups/update/$1'),'Ubah');
            if ($hakAkses['hapus']) {
                $action .= " | ";
            }
        }
        if ($hakAkses['hapus']) {
            $action .= anchor(site_url('t86_groups/delete/$1'),'Hapus','onclick="javascript: return confirm(\'Apakah Anda yakin ingin menghapus data ?\')"');
        }
        $this->datatables->add_column('action', $action, 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
		$this->db->or_like('name', $q);
		$this->db->or_like('description', $q);
		$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
		$this->db->or_like('name', $q);
		$this->db->or_like('description', $q);
		$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file T86_groups_model.php */
/* Location: ./application/models/T86_groups_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-11-23 10:09:36 */
/* http://harviacode.com */